### ISSUE TITLE
Normal Emoji doesn't properly set

### ISSUE THREAD

**Issue by MirayXS** [Jxyme/covid-19-discord-custom-status#2]
# Normal Emoji doesn't properly set

### My config.json:

```JSON
{
    "token": "USER_TOKEN",
    "country": "it",
    "emojiID": null,
    "emojiName": "mask"
}
```

![image](https://user-images.githubusercontent.com/55494819/89135581-d2cbb980-d52e-11ea-9518-58f8ba8c9442.png)

**Comment by MirayXS** [comment]
Maybe it takes the old emoji from a old custom status?

I had a custom status that had no emoji.

**Comment by Jxyme** [comment]
> I had a custom status that had no emoji.

If you previously had no emoji and the figures remain the same after you added “😷”, the emoji won’t yet apply automatically since the status only updates when new figures are detected.

You can either wait until figures reset (on a new day) or force the new status by modifying one of the values in `data.json` so that it differs from the API response.

**Comment by Jxyme** [comment]
> > I had a custom status that had no emoji.
> 
> If you previously had no emoji and the figures remain the same after you added “😷”, the emoji won’t yet apply automatically since the status only updates when new figures are detected.
> 
> You can either wait until figures reset (on a new day) or force the new status by modifying one of the values in `data.json` so that it differs from the API response.

After some testing it appears the Custom Status is no-longer accepting Shortcodes (e.g. `mask`, `:mask:`) and instead requires the emoji character itself. I will *try* and work around this, though I'm not entirely sure whether it's possible at this moment in time.

For the time being, if you'd like to use "😷" or any other standard emoji, you can copy/paste the emoji character from [Emojipedia](https://emojipedia.org/emoji/%F0%9F%98%B7/).

Apologies for that, I will update the [README](https://github.com/Jxyme/covid-19-discord-custom-status#readme) example which demonstrates this too.

**Comment by MirayXS** [comment]
Alright, ty!
